# Generated by Django 6.0.1 on 2026-04-19 21:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_resume_related_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='changefreq',
            field=models.CharField(choices=[('always', 'Always'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('never', 'Never')], default='monthly', max_length=20, verbose_name='فرکانس تغییر'),
        ),
        migrations.AddField(
            model_name='resume',
            name='seo_priority',
            field=models.DecimalField(decimal_places=1, default=0.4, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='اولویت سئو'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='is_confirmed',
            field=models.BooleanField(default=True, verbose_name='وضعیت نمایش و انتشار در سایت مپ'),
        ),
    ]
