# Generated by Django 6.0.1 on 2026-04-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_resume_changefreq_resume_seo_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='visit_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
